### ISSUE TITLE
Negative int (or long) value deserialized incorrectly

### ISSUE THREAD

**Issue by chrisCesar34** [arangodb/arangodb-java-driver#151]
We are using ArangoDB version 3.2.3 and Java Driver version 4.2.4, on Mac OS X 10.12.6

We have java objects with a long (or int) filed. When storing negative values for these fields, if we check the database content with ArangoDB web interface, the collection contains a vertex with the good negative value.

If we test our request for getting our objects thanks to ArangoDB web interface, the resulting JSON structure also contains the good negative value.

But if we use Arango Java Driver, the resulting value is incorrect. For example, when storing -50 as long, the returned value is 206.

Thanks for fixing it ... or helping to understand why it happens.

**Comment by gontard** [comment]
Hello @mpv1989 ,

i work we @chrisCesar34 .
To reproduce the issue, i followed these steps.

1) I made a [dump](https://github.com/arangodb/arangodb-java-driver/files/1362175/dump.zip) of a collection named "nodes":

`arangodump --collection nodes`

2) I restored it in a 'TEST' database:

`arangorestore --server.database TEST --create-collection true --import-data true --input-directory ./dump`

3) I checked the import: the collections contains a single document with two negative attributes values: 

      arangosh --server.database TEST
      db._document('nodes/1875024-1')
      {
        "_key" : "1875024-1",
        "_id" : "nodes/1875024-1",
        "_rev" : "_VtBtG5u---",
        "x" : -100,
        "y" : -300
      }

4) I wrote a test extending the `BaseTest` class:

        @RunWith(Parameterized.class)
        public class LoadNegativeIntTest extends BaseTest {
            public LoadNegativeIntTest(ArangoDB.Builder builder) {
                super(builder);
            }

            @Test
            public void loadNegativeInt() throws Exception {
                BaseDocument document = arangoDB.db("TEST")
                        .collection("nodes").getDocument("1875024-1", BaseDocument.class);
                assertEquals(-100L, document.getAttribute("x"));
                assertEquals(-300L, document.getAttribute("y"));
            }
        }


5) **The test pass with the `Protocol.HTTP_JSON`but fails with the `Protocol.VST` and `Protocol.HTTP_VPACK`**

I tried with the `com.arangodb:velocypack:1.0.12-SNAPSHOT` and the result is the same.

Any ideas ?

**Comment by mpv1989** [comment]
@gontard Fixed in version 4.2.6

**Comment by lorling88** [comment]
Hi,

I will like to add on to this issue raised as my issue is quite similar.
After running the latest java driver 4.2.6 on Arangodb 3.2.4, my issue is still not fixed.

As attached is the example database dump with the java class file.
From the result, negative whole numbers without decimal points will retrieve incorrect numbers.
You should see the "key1" and "key5" value are incorrect.

Please kindly assist.
Thanks alot!

[negative.zip](https://github.com/arangodb/arangodb-java-driver/files/1409545/negative.zip)

**Comment by mpv1989** [comment]
@lorling88 Hi,

I tried to reproduce your problem with your data and programm. My output is:
```
jsonKey1 === {"_id":"negative\/key1","_key":"key1","_rev":"_VygzC_q---","value":-100} - value should be -100
jsonKey2 === {"_id":"negative\/key2","_key":"key2","_rev":"_VygzgYq---","value":-100.01} - value should be -100.01
jsonKey3 === {"_id":"negative\/key3","_key":"key3","_rev":"_VyhhmRe---","value":-100.1} - value should be -100.1
jsonKey4 === {"_id":"negative\/key4","_key":"key4","_rev":"_Vyg0I0u---","value":100.01} - value should be 100.01
jsonKey5 === {"_id":"negative\/key5","_key":"key5","_rev":"_Vyg0X-----","value":-999} - value should be -999
```

Are you sure you used driver version `4.2.6`?

**Comment by lorling88** [comment]
Hi,

My apologies and you are right.
I misplaced the latest velocypack 1.0.12 previously, got it sorted and its working correctly now.
Thanks!

I have a question if you don't mind helping me with it as it has been bothering me for quite sometime.
This is regards to serializing numbers and map into BigDecimal types.
Attached the example, the stored value is "-710.01", however when it got serialized into a BigDecimal type, the value stored inside became "-710.009999999999990905052982270717620849609375".

As for now i had to force BigDecimal to round and rounding does not give me the true value as stored inside the collection.

Is there any advise i can get from you to retain the same value of "-710.01" inside a BigDecimal?


[negative2.zip](https://github.com/arangodb/arangodb-java-driver/files/1410328/negative2.zip)

**Comment by mpv1989** [comment]
@lorling88 I changed the deserialization of BigDecimal in com.arangodb:velocypack module (see [here](https://github.com/arangodb/java-velocypack/commit/00a0ef347f53db014c3b73da72607f5044e26a00)).

You can test this by using version `1.0.13-SNAPSHOT` of that dependency.
```
<dependency>
  <groupId>com.arangodb</groupId>
  <artifactId>velocypack</artifactId>
  <version>1.0.13-SNAPSHOT</version>
</dependency>
```

**Comment by ochando** [comment]
Hello,

This issue seems not fixed when the method getDocument() is called using class String as second parameter, for example:
`String document = collection.getDocument(vertex.getKey(), String.class);`

A persisted long value -62135596800, is retrieved as -2006054656 by the driver.

I really need to parse the JSON myself, because of my serialization library.

I'm using ArangoDB version 3.2.3 and Arango Java Driver:

>         <dependency>
>             <groupId>com.arangodb</groupId>
>             <artifactId>arangodb-java-driver</artifactId>
>             <version>4.2.7</version>
>             <exclusions>
>                 <exclusion>
>                     <groupId>com.arangodb</groupId>
>                     <artifactId>velocypack</artifactId>
>                 </exclusion>
>             </exclusions>
>         </dependency>
>         <dependency>
>             <groupId>com.arangodb</groupId>
>             <artifactId>velocypack</artifactId>
>             <version>1.0.13-SNAPSHOT</version>
>         </dependency>

**Comment by mpv1989** [comment]
Thanks for reporting!

Fixed it in version 4.3.1 which I just released.
